"""add phonenumber

Revision ID: e3e6342ee028
Revises: 3ebe06bd7d23
Create Date: 2025-09-16 16:32:59.718297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3e6342ee028'
down_revision: Union[str, Sequence[str], None] = '3ebe06bd7d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersTable', sa.Column('phone_number', sa.String(length=255), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersTable', 'phone_number')
    pass
    # ### end Alembic commands ###
